apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: dqm01
  template:
    pod:
      containers:
        - env:
            - name: MQ_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dqm01-admin-password
                  key: admin-password
