apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mq01-secret1
  namespace: mq01-dev
spec:
  dnsNames:
    - jb3dummy.domain.com
  secretName: mq01-qmgr-cert
  issuerRef:
    name: mq-selfsigned-issuer
  duration: 1992h0m0s # 83 days
  renewBefore: 30m0s # 0,5 days
  subject:
    organizations:
      - mq-org
# The use of the common name field has been deprecated since 2000 and is
# discouraged from being used.
  commonName: jb3dummy.domain.com
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 4096
  usages:
    - server auth
    - client auth
  privateKey:
    rotationPolicy: Always
    
